// app/src/components/Input.vue
<template>
  <label :for="id">
    {{ labelText }}
    <input
      :value="modelValue"
      @change="$emit('update:modelValue', $event.target.value)"
      :id="id"
    />
  </label>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'Input',
  props: {
    id: String,
    labelText: String,
    modelValue: String,
  },
});
</script>

<style scoped lang="sass">

</style>

// app/src/components/Input/Input.tsx
import "./Input.sass";

type Props = {
  label?: string;
  type: string;
  placeholder: string;
  action: Function;
};

export default function Input({ label, type, placeholder, action }: Props) {
  return (
    <div className="input">
      {label && (
        <label className="input-label" htmlFor="input">
          {label}
        </label>
      )}
      <input
        className="input-input"
        type={type}
        placeholder={placeholder}
        onChange={(event) => action(event.target.value)}
      />
    </div>
  );
}
